---
apiVersion: v1
kind: Service
metadata:
  annotations:
    jkube.eclipse.org/scm-url: https://github.com/spring-projects/spring-boot/spring-boot-with-jkube
    jkube.eclipse.org/scm-tag: HEAD
    jkube.eclipse.org/git-commit: 6f493fbc6aa9cdf59ddcf0012ac0b762d81a77a8
    jkube.eclipse.org/git-url: https://github.com/Nazjara/spring-boot-with-jkube.git
    jkube.eclipse.org/git-branch: master
  labels:
    app: spring-boot-with-jkube
    provider: jkube
    version: 1.0.0-SNAPSHOT
    group: com.nazjara
    app.kubernetes.io/part-of: com.nazjara
    app.kubernetes.io/managed-by: jkube
    app.kubernetes.io/name: spring-boot-with-jkube
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: spring-boot-with-jkube
spec:
  ports:
  - name: http
    nodePort: 30080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: spring-boot-with-jkube
    provider: jkube
    group: com.nazjara
    app.kubernetes.io/name: spring-boot-with-jkube
    app.kubernetes.io/part-of: com.nazjara
    app.kubernetes.io/managed-by: jkube
  type: NodePort
